import Link from "next/link";
import { Alert, Card, EmptyState } from "@/components/ui/surfaces";
import { Button } from "@/components/ui/button";
import type { getDashboardOverview } from "@/server/dashboard/overview";

type Overview = Awaited<ReturnType<typeof getDashboardOverview>>;
function formatMinor(amount:number,currency:string){return new Intl.NumberFormat("en-US",{style:"currency",currency}).format(amount/100)}

export function DashboardOverview({ overview }: { overview: Overview }) {
  const customer=overview.customer;
  return <>
    {!customer&&<Alert title="Complete registration">Create your customer profile before product features become available. <Link className="font-semibold text-action underline" href="/register">Start registration</Link></Alert>}
    {customer&&customer.verification_status!=="verified"&&<Alert title="Verification required">Complete identity verification before future account actions. <Link className="font-semibold text-action underline" href="/register?step=verification">Continue verification</Link></Alert>}
    {customer?.verification_status==="verified"&&<Alert title="Identity verification complete" tone="success">Your identity verification is complete.</Alert>}
    {customer?.account_status&&customer.account_status!=="active"&&<Alert title="Account access is restricted" tone="error">Customer status: {customer.account_status}.</Alert>}
    <section id="accounts" className="mt-8" aria-labelledby="accounts-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wider text-action">Overview</p><h2 id="accounts-heading" className="mt-2 text-2xl font-semibold">Your products</h2></div><p className="text-sm text-muted">New accounts start at zero. Posted balances begin in Phase 8.</p></div>
      {overview.accounts.length===0&&overview.productCounts.credit===0&&overview.productCounts.loans===0&&overview.productCounts.investments===0?<div className="mt-5"><EmptyState title="No banking products yet"><p>Checking and savings account creation begins in Phase 7. New accounts will start at a real zero balance.</p><Link className="mt-4 inline-flex min-h-11 items-center font-semibold text-action underline" href="/checking">Explore checking</Link></EmptyState></div>:<div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        {overview.accounts.map((account)=><Card key={account.id}><p className="text-xs font-semibold uppercase text-muted">{account.account_type}</p><h3 className="mt-2 text-lg font-semibold"><Link className="text-action underline" href={`/accounts/${account.id}`}>{account.nickname}</Link></h3><p className="mt-2 text-sm text-muted">{account.masked_account_number} · {account.status}</p><p className="mt-4 font-semibold tabular-nums">{formatMinor(account.balance?.available_balance_minor??0,account.currency)} available</p></Card>)}
        {overview.productCounts.credit>0&&<Card><h3 className="font-semibold">Credit cards</h3><p className="mt-2 text-2xl font-semibold">{overview.productCounts.credit}</p></Card>}{overview.productCounts.loans>0&&<Card><h3 className="font-semibold"><Link className="text-action underline" href="/loans">Loans</Link></h3><p className="mt-2 text-2xl font-semibold">{overview.productCounts.loans}</p></Card>}{overview.productCounts.investments>0&&<Card><h3 className="font-semibold">Investments</h3><p className="mt-2 text-2xl font-semibold">{overview.productCounts.investments}</p></Card>}
      </div>}
    </section>
    <section id="actions" className="mt-10" aria-labelledby="actions-heading"><h2 id="actions-heading" className="text-2xl font-semibold">Quick actions</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{customer?.verification_status==="verified"&&customer.account_status==="active"&&<><Card className="p-4"><Link className="inline-flex min-h-11 w-full items-center justify-center rounded-control bg-action px-4 py-2 font-semibold text-white" href="/transfers/new">Transfer money</Link><p className="mt-2 text-center text-xs text-muted">Your accounts and saved recipients</p></Card><Card className="p-4"><Link className="inline-flex min-h-11 w-full items-center justify-center rounded-control bg-action px-4 py-2 font-semibold text-white" href="/receive-money">Receive money</Link><p className="mt-2 text-center text-xs text-muted">Provider integrations awaiting approved activation</p></Card><Card className="p-4"><Link className="inline-flex min-h-11 w-full items-center justify-center rounded-control bg-action px-4 py-2 font-semibold text-white" href="/bill-pay/new">Pay bills</Link><p className="mt-2 text-center text-xs text-muted">Immediate and scheduled payments</p></Card><Card className="p-4"><Link className="inline-flex min-h-11 w-full items-center justify-center rounded-control bg-action px-4 py-2 font-semibold text-white" href="/cards">Manage cards</Link><p className="mt-2 text-center text-xs text-muted">Balances, purchases and controls</p></Card><Card className="p-4"><Link className="inline-flex min-h-11 w-full items-center justify-center rounded-control bg-action px-4 py-2 font-semibold text-white" href="/check-deposit/new">Deposit check</Link><p className="mt-2 text-center text-xs text-muted">Upload and review your check</p></Card><Card className="p-4"><Link className="inline-flex min-h-11 w-full items-center justify-center rounded-control bg-action px-4 py-2 font-semibold text-white" href="/statements/new">Generate statement</Link><p className="mt-2 text-center text-xs text-muted">Private ledger-derived PDF</p></Card><Card className="p-4"><Link className="inline-flex min-h-11 w-full items-center justify-center rounded-control bg-action px-4 py-2 font-semibold text-white" href="/loans">Manage loans</Link><p className="mt-2 text-center text-xs text-muted">Personal and auto loans</p></Card></>}<Card className="p-4">{customer?.verification_status==="verified"&&customer.account_status==="active"?<><Link className="inline-flex min-h-11 w-full items-center justify-center rounded-control bg-action px-4 py-2 font-semibold text-white" href="/accounts/new">Open account</Link><p className="mt-2 text-center text-xs text-muted">Checking and savings available</p></>:<><Button className="w-full" variant="secondary" disabled>Open account</Button><p className="mt-2 text-center text-xs text-muted">Complete registration and verification</p></>}</Card></div></section>
    <div className="mt-10 grid gap-6 lg:grid-cols-2"><section aria-labelledby="activity-heading"><h2 id="activity-heading" className="text-2xl font-semibold">Recent transactions</h2><div className="mt-5">{overview.transactions.length===0?<EmptyState title="No transactions yet">Posted account activity will appear here after ledger-backed accounts and operations exist.</EmptyState>:<div className="space-y-3">{overview.transactions.map((item)=><Card key={item.id} className="flex items-center justify-between gap-4"><div><h3 className="font-semibold">{item.description}</h3><p className="text-sm text-muted">{item.status}</p></div><p className="font-semibold tabular-nums">{item.direction==="debit"?"−":"+"}{formatMinor(item.amount_minor,item.currency)}</p></Card>)}</div>}</div></section>
      <section aria-labelledby="payments-heading"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="payments-heading" className="text-2xl font-semibold">Upcoming payments</h2><Link className="font-semibold text-action underline" href="/bill-pay">View Bill Pay</Link></div><div className="mt-5">{overview.payments.length===0?<EmptyState title="No upcoming payments">Schedule a bill payment and it will appear here.</EmptyState>:<div className="space-y-3">{overview.payments.map((item)=><Card key={item.id}><p className="font-semibold tabular-nums">{formatMinor(item.amount_minor,item.currency)}</p><p className="text-sm text-muted">{item.status} · {item.scheduled_at?.slice(0,10)}</p></Card>)}</div>}</div></section>
    </div>
    <section id="alerts" className="mt-10" aria-labelledby="alerts-heading"><h2 id="alerts-heading" className="text-2xl font-semibold">Alerts</h2><div className="mt-5">{overview.notifications.length===0?<EmptyState title="No alerts">Security and product notifications will appear here when an implemented workflow creates them.</EmptyState>:<div className="space-y-3">{overview.notifications.map((item)=><Alert key={item.id} title={item.title}>{item.body}</Alert>)}</div>}</div></section>
  </>;
}
