import Link from "next/link";
import { BankLogo } from "@/components/ui/bank-logo";

const groups: Array<{ title: string; links: Array<[string,string]> }> = [
  {title:"Personal",links:[["Checking","/checking"],["Savings","/savings"],["Credit Cards","/credit-cards"],["Home Loans","/mortgage"],["Auto","/auto-financing"],["Investing","/investing"]]},
  {title:"Resources",links:[["Education","/education"],["Security","/security"],["Help center","/help-center"],["FAQ","/faq"],["Contact","/contact"]]},
  {title:"Project",links:[["About","/about"],["Privacy","/privacy"],["Terms","/terms"],["Business","/business-banking"],["Commercial","/commercial"]]},
];
export function SiteFooter(){return <footer className="mt-auto border-t border-border bg-brand text-white"><div className="mx-auto grid max-w-public gap-8 px-4 py-10 sm:grid-cols-2 sm:px-6 lg:grid-cols-4 lg:px-8"><div><BankLogo/><p className="mt-4 text-sm text-white/80">A development portfolio application demonstrating secure banking software architecture.</p><p className="mt-4 text-xs leading-5 text-white/75">Chaze Bank is not a chartered or regulated financial institution. It does not hold deposits, issue real cards, or move real money. Use synthetic information only.</p></div>{groups.map((group)=><nav key={group.title} aria-label={`${group.title} footer navigation`}><h2 className="font-semibold">{group.title}</h2><ul className="mt-3 space-y-2 text-sm">{group.links.map(([label,href])=><li key={href}><Link className="text-white/85 underline-offset-4 hover:underline" href={href}>{label}</Link></li>)}</ul></nav>)}</div><div className="border-t border-white/20"><p className="mx-auto max-w-public px-4 py-5 text-xs text-white/70 sm:px-6 lg:px-8">© {new Date().getFullYear()} Chaze Bank application project. Not affiliated with JPMorgan Chase &amp; Co. or any other financial institution.</p></div></footer>}
