import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Alert, Card, EmptyState } from "@/components/ui/surfaces";
import { Select } from "@/components/ui/fields";
import { requireVerifiedIdentity } from "@/server/auth/identity";
import { payMortgageAction } from "@/server/mortgages/actions";
import { getCurrentMortgage } from "@/server/mortgages/queries";
function money(value: number, currency: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(value / 100); }
export default async function MortgageDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ message?: string }> }) {
  await requireVerifiedIdentity(); const [{ id }, query] = await Promise.all([params, searchParams]); const item = await getCurrentMortgage(id); if (!item) notFound();
  return <main id="main-content" className="mx-auto w-full max-w-5xl px-4 py-10 sm:px-6"><Link className="font-semibold text-action underline" href="/mortgages">Back to mortgages</Link>{query.message && <div className="mt-5"><Alert title={query.message === "approved" ? "Mortgage approved" : query.message === "paid" ? "Payment posted" : "Payment not completed"} tone={query.message === "failed" ? "error" : "success"}/></div>}<div className="mt-8 flex flex-wrap justify-between gap-5"><div><p className="text-sm font-semibold uppercase tracking-widest text-action">Mortgage</p><h1 className="mt-2 text-3xl font-semibold">{money(item.balance?.outstanding_minor ?? 0, item.currency)} outstanding</h1><p className="mt-2 text-muted">{(item.rate * 100).toFixed(2)}% fixed APR · {item.term_months} months</p></div><div className="text-right"><p className="text-sm text-muted">Monthly payment</p><p className="text-2xl font-semibold">{money(item.monthly_payment_minor, item.currency)}</p><p className="text-sm text-muted">Due {item.next_due_date ?? "Paid off"}</p></div></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-semibold">Balance details</h2><dl className="mt-5 grid grid-cols-2 gap-4"><div><dt className="text-sm text-muted">Original principal</dt><dd className="font-semibold">{money(item.principal_minor, item.currency)}</dd></div><div><dt className="text-sm text-muted">Escrow balance</dt><dd className="font-semibold">{money(item.balance?.escrow_balance_minor ?? 0, item.currency)}</dd></div><div><dt className="text-sm text-muted">Monthly escrow</dt><dd className="font-semibold">{money(item.escrow_monthly_minor, item.currency)}</dd></div><div><dt className="text-sm text-muted">Monthly interest</dt><dd className="font-semibold">{money(item.balance?.accrued_interest_minor ?? 0, item.currency)}</dd></div></dl></Card><Card><h2 className="text-xl font-semibold">Make a payment</h2>{item.status === "active" ? <form action={payMortgageAction} className="mt-5 space-y-4"><input type="hidden" name="mortgageId" value={item.id}/><input type="hidden" name="commandKey" value={randomUUID()}/><Select name="account" label="Pay from" required defaultValue=""><option value="" disabled>Select account</option>{item.fundingAccounts.map((account) => <option key={account.id} value={account.id}>{account.nickname} {account.masked_account_number} — {money(account.balance?.available_balance_minor ?? 0, account.currency)}</option>)}</Select><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Pay {money(item.monthly_payment_minor, item.currency)}</button></form> : <Alert title="Mortgage paid off" tone="success"/>}</Card></div>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Payment history</h2>{item.mortgage_payments.length === 0 ? <div className="mt-4"><EmptyState title="No payments yet">Principal, interest and escrow splits will appear here.</EmptyState></div> : <div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{item.mortgage_payments.map((payment) => <div className="flex flex-wrap justify-between gap-4 p-4" key={payment.id}><div><p className="font-semibold">{payment.accounts?.nickname ?? "Deposit account"}</p><p className="text-sm text-muted">{new Date(payment.paid_at ?? payment.created_at).toLocaleString("en-US")}</p></div><p className="text-sm">Principal {money(payment.principal_minor, item.currency)} · Interest {money(payment.interest_minor, item.currency)} · Escrow {money(payment.escrow_minor, item.currency)}</p></div>)}</div>}</section>
  </main>;
}
