import Link from "next/link";
import { Input, Select } from "@/components/ui/fields";
import { Alert, Card, EmptyState } from "@/components/ui/surfaces";
import { MfaManager } from "@/features/security-center/mfa-manager";
import { requireVerifiedIdentity } from "@/server/auth/identity";
import { registerDeviceAction, revokeDeviceAction, revokeSessionAction } from "@/server/security-center/actions";
import { getSecurityCenter } from "@/server/security-center/queries";

const messages: Record<string,string> = { "device-saved": "This device is registered", "session-revoked": "Session revoked", "device-revoked": "Device revoked" };
function date(value: string | null) { return value ? new Date(value).toLocaleString("en-US") : "—"; }

export default async function SecurityCenterPage({ searchParams }: { searchParams: Promise<{ message?: string }> }) {
  await requireVerifiedIdentity(); const [data, query] = await Promise.all([getSecurityCenter(), searchParams]); const currentSession = data.sessions.find((session) => session.id === data.currentSessionId); const currentDeviceId = currentSession?.device_id ?? null; const aal2 = data.currentLevel === "aal2"; const successMessage = query.message ? messages[query.message] : undefined;
  return <main id="main-content" className="mx-auto w-full max-w-6xl px-4 py-10 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-action">Account protection</p><h1 className="mt-2 text-3xl font-semibold">Security Center</h1><p className="mt-2 text-muted">Manage authenticator MFA, recognized devices, sessions and security history.</p></div><Link className="font-semibold text-action underline" href="/dashboard">Back to dashboard</Link></div>
    {query.message && <div className="mt-6">{successMessage ? <Alert title={successMessage} tone="success"/> : query.message === "step-up-required" ? <Alert title="MFA verification required">Use the authenticator section below, then retry the security action.</Alert> : <Alert title="Security action incomplete" tone="error">Review your current session and try again.</Alert>}</div>}
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-semibold">Authenticator MFA</h2><p className="mt-2 text-sm text-muted">An authenticator app protects sensitive settings and staff actions. Verification elevates only the current provider session.</p><MfaManager factors={data.factors} currentLevel={data.currentLevel}/></Card>
      <Card><h2 className="text-xl font-semibold">Register this device</h2><p className="mt-2 text-sm text-muted">Device recognition is convenience metadata and never replaces MFA.</p><form action={registerDeviceAction} className="mt-5 space-y-4"><Input name="label" label="Device name" required maxLength={120} placeholder="My laptop"/><Select name="trustDays" label="Remember for" defaultValue="30"><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></Select><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Register this device</button></form></Card></div>
    <section className="mt-8" aria-labelledby="sessions-heading"><h2 id="sessions-heading" className="text-2xl font-semibold">Sessions</h2>{data.sessions.length === 0 ? <div className="mt-4"><EmptyState title="No sessions">Active application sessions will appear here.</EmptyState></div> : <div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{data.sessions.map((session) => { const device = data.devices.find((item) => item.id === session.device_id); const current = session.id === data.currentSessionId; return <article className="flex flex-wrap items-center justify-between gap-4 p-4" key={session.id}><div><h3 className="font-semibold">{current ? "Current session" : device?.label ?? "Unrecognized session"}</h3><p className="text-sm text-muted">Last active {date(session.last_seen_at)} · Expires {date(session.expires_at)}</p><p className="text-sm text-muted">{session.revoked_at ? `Revoked ${date(session.revoked_at)}` : "Active"}</p></div>{!current && !session.revoked_at && <form action={revokeSessionAction}><input type="hidden" name="sessionId" value={session.id}/><button disabled={!aal2} className="min-h-11 rounded-control bg-danger px-4 font-semibold text-white disabled:opacity-50">Revoke session</button></form>}</article>; })}</div>}</section>
    <section className="mt-8" aria-labelledby="devices-heading"><h2 id="devices-heading" className="text-2xl font-semibold">Recognized devices</h2>{data.devices.length === 0 ? <div className="mt-4"><EmptyState title="No recognized devices">Register this browser if you want it listed here.</EmptyState></div> : <div className="mt-4 grid gap-4 sm:grid-cols-2">{data.devices.map((device) => <Card key={device.id}><h3 className="font-semibold">{device.label}{device.id === currentDeviceId ? " · current" : ""}</h3><p className="mt-2 text-sm text-muted">Trusted until {date(device.trusted_until)}</p><p className="text-sm text-muted">Added {date(device.created_at)}</p>{device.revoked_at ? <p className="mt-3 font-semibold text-danger">Revoked</p> : device.id !== currentDeviceId && <form action={revokeDeviceAction} className="mt-4"><input type="hidden" name="deviceId" value={device.id}/><button disabled={!aal2} className="min-h-11 rounded-control bg-danger px-4 font-semibold text-white disabled:opacity-50">Revoke device</button></form>}</Card>)}</div>}</section>
    <section className="mt-8" aria-labelledby="history-heading"><h2 id="history-heading" className="text-2xl font-semibold">Security history</h2>{data.events.length === 0 ? <div className="mt-4"><EmptyState title="No security events">Sign-ins and security changes will appear here.</EmptyState></div> : <div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{data.events.map((event) => <article className="grid gap-1 p-4 sm:grid-cols-[1fr_auto]" key={`${event.category}-${event.id}`}><div><h3 className="font-semibold capitalize">{event.event_type.replaceAll("_", " ")}</h3><p className="text-sm text-muted">{event.category} · {event.outcome}{event.reason_code ? ` · ${event.reason_code}` : ""}</p></div><time className="text-sm text-muted">{date(event.occurred_at)}</time></article>)}</div>}</section>
  </main>;
}
