"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/fields";
import { Alert } from "@/components/ui/surfaces";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";

type Factor = { id: string; friendlyName: string; status: string };
export function MfaManager({ factors, currentLevel }: { factors: Factor[]; currentLevel: string | null }) {
  const router = useRouter(); const [factorId, setFactorId] = useState<string | null>(null); const [qr, setQr] = useState<string | null>(null); const [secret, setSecret] = useState<string | null>(null); const [code, setCode] = useState(""); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const supabase = createBrowserSupabaseClient();
  const firstFactor = factors[0];
  async function enroll() { setBusy(true); setMessage(null); const result = await supabase.auth.mfa.enroll({ factorType: "totp", friendlyName: `BANK authenticator ${new Date().toLocaleDateString()}` }); setBusy(false); if (result.error) return setMessage("Authenticator setup could not start."); setFactorId(result.data.id); setQr(result.data.totp.qr_code); setSecret(result.data.totp.secret); }
  async function verify(id: string) { if (!/^\d{6}$/.test(code)) return setMessage("Enter the six-digit code from your authenticator app."); setBusy(true); setMessage(null); const challenge = await supabase.auth.mfa.challenge({ factorId: id }); if (challenge.error) { setBusy(false); return setMessage("The verification challenge could not start."); } const verified = await supabase.auth.mfa.verify({ factorId: id, challengeId: challenge.data.id, code }); if (verified.error) { setBusy(false); return setMessage("That code was not accepted. Try the newest code."); } await supabase.rpc("record_current_security_event", { p_event_type: factorId === id ? "mfa_enrolled" : "mfa_verified" }); setBusy(false); router.refresh(); }
  async function remove(id: string) { setBusy(true); setMessage(null); const result = await supabase.auth.mfa.unenroll({ factorId: id }); if (!result.error) await supabase.rpc("record_current_security_event", { p_event_type: "mfa_unenrolled" }); setBusy(false); if (result.error) return setMessage("Step up with MFA before removing a factor."); router.refresh(); }
  return <div className="mt-5 space-y-5">{message && <Alert title="Security action incomplete" tone="error">{message}</Alert>}{factors.length === 0 && !factorId && <Button pending={busy} onClick={enroll}>Set up authenticator app</Button>}{qr && factorId && <div className="space-y-4"><p className="text-sm text-muted">Scan this code in an authenticator app, or enter the setup key manually.</p><img className="size-48 rounded-control border border-border bg-white p-2" src={qr} alt="Authenticator setup QR code"/><p className="break-all rounded-control bg-subtle p-3 font-mono text-sm">{secret}</p><Input label="Six-digit verification code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))}/><Button pending={busy} onClick={() => verify(factorId)}>Verify and enable MFA</Button></div>}{firstFactor && currentLevel !== "aal2" && <div className="space-y-4"><Alert title="Step-up required">Enter a current authenticator code to manage sessions, devices or factors.</Alert><Input label="Six-digit authenticator code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))}/><Button pending={busy} onClick={() => verify(firstFactor.id)}>Verify this session</Button></div>}{factors.length > 0 && currentLevel === "aal2" && <div className="space-y-3">{factors.map((factor) => <div className="flex flex-wrap items-center justify-between gap-3 rounded-control border border-border p-3" key={factor.id}><div><p className="font-semibold">{factor.friendlyName}</p><p className="text-sm capitalize text-muted">{factor.status}</p></div><Button variant="destructive" pending={busy} onClick={() => remove(factor.id)}>Remove</Button></div>)}</div>}</div>;
}
