import { randomUUID } from "node:crypto";
import Link from "next/link";
import { Alert, Card, EmptyState } from "@/components/ui/surfaces";
import { Input, Select } from "@/components/ui/fields";
import { requireVerifiedIdentity } from "@/server/auth/identity";
import { fundInvestmentAccountAction, openInvestmentAccountAction, tradeInvestmentAction } from "@/server/investments/actions";
import { getInvestmentDashboard } from "@/server/investments/queries";
function money(value: number, currency = "USD") { return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(value / 100); }
export default async function InvestmentsPage({ searchParams }: { searchParams: Promise<{ message?: string }> }) {
  await requireVerifiedIdentity(); const [data, query] = await Promise.all([getInvestmentDashboard(), searchParams]);
  const total = (data.overview?.cash_minor ?? 0) + (data.overview?.market_value_minor ?? 0);
  return <main id="main-content" className="mx-auto w-full max-w-6xl px-4 py-10 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-action">Investing</p><h1 className="mt-2 text-3xl font-semibold">Investments</h1><p className="mt-2 text-muted">Review cash, holdings, market values and recent activity in one place.</p></div><Link className="font-semibold text-action underline" href="/dashboard">Back to dashboard</Link></div>
    {query.message && <div className="mt-5"><Alert title={query.message === "failed" ? "Action not completed" : "Investment account updated"} tone={query.message === "failed" ? "error" : "success"}/></div>}
    {!data.account ? <div className="mt-8"><EmptyState title="No investment account"><p>Open an investment account to begin.</p><form action={openInvestmentAccountAction}><button className="mt-4 min-h-11 rounded-control bg-action px-4 font-semibold text-white">Open investment account</button></form></EmptyState></div> : <>
      <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Card><p className="text-sm text-muted">Total value</p><p className="mt-2 text-2xl font-semibold">{money(total)}</p></Card><Card><p className="text-sm text-muted">Investment cash</p><p className="mt-2 text-2xl font-semibold">{money(data.overview?.cash_minor ?? 0)}</p></Card><Card><p className="text-sm text-muted">Holdings value</p><p className="mt-2 text-2xl font-semibold">{money(data.overview?.market_value_minor ?? 0)}</p></Card><Card><p className="text-sm text-muted">Cost basis</p><p className="mt-2 text-2xl font-semibold">{money(data.overview?.cost_basis_minor ?? 0)}</p></Card></div>
      <div className="mt-8 grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-semibold">Add investment cash</h2><form action={fundInvestmentAccountAction} className="mt-5 space-y-4"><input type="hidden" name="investmentId" value={data.account.id}/><input type="hidden" name="commandKey" value={randomUUID()}/><Select name="account" label="Transfer from" required defaultValue=""><option value="" disabled>Select account</option>{data.fundingAccounts.map((account) => <option key={account.id} value={account.id}>{account.nickname} — {money(account.balance?.available_balance_minor ?? 0)}</option>)}</Select><Input name="amount" label="Amount" required inputMode="decimal"/><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Transfer cash</button></form></Card><Card><h2 className="text-xl font-semibold">Place a trade</h2><form action={tradeInvestmentAction} className="mt-5 space-y-4"><input type="hidden" name="investmentId" value={data.account.id}/><input type="hidden" name="commandKey" value={randomUUID()}/><Select name="instrument" label="Instrument" required defaultValue=""><option value="" disabled>Select instrument</option>{data.instruments.map((item) => <option key={item.id} value={item.id}>{item.symbol} — {item.name} — {money(Math.round(item.price * 100))}</option>)}</Select><Select name="kind" label="Action" required defaultValue="buy"><option value="buy">Buy</option><option value="sell">Sell</option></Select><Input name="quantity" label="Quantity" required inputMode="decimal"/><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Submit trade</button></form></Card></div>
      <section className="mt-10"><h2 className="text-2xl font-semibold">Holdings</h2>{data.holdings.length === 0 ? <div className="mt-4"><EmptyState title="No holdings">Fund the account and buy an investment.</EmptyState></div> : <div className="mt-4 overflow-hidden rounded-card border border-border bg-surface">{data.holdings.map((item) => <div className="grid gap-3 border-b border-border p-4 last:border-0 sm:grid-cols-[1fr_auto]" key={item.id}><div><p className="font-semibold">{item.instrument?.symbol} · {item.instrument?.name}</p><p className="text-sm text-muted">{item.quantity} units</p></div><div className="text-right"><p className="font-semibold">{money(Math.round(Number(item.quantity) * Number(item.instrument?.price ?? 0) * 100))}</p><p className="text-sm text-muted">Cost {money(item.cost_basis_minor)}</p></div></div>)}</div>}</section>
      <section className="mt-10"><h2 className="text-2xl font-semibold">Activity</h2>{data.transactions.length === 0 ? <p className="mt-3 text-muted">No investment activity yet.</p> : <div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{data.transactions.map((item) => <div className="flex flex-wrap justify-between gap-4 p-4" key={item.id}><div><p className="font-semibold capitalize">{item.kind} {item.instrument?.symbol ?? "cash"}</p><p className="text-sm text-muted">{new Date(item.occurred_at).toLocaleString("en-US")}</p></div><p className="font-semibold">{money(item.cash_amount_minor, item.currency)}</p></div>)}</div>}</section>
    </>}
  </main>;
}
