import Link from "next/link";
import { Card, EmptyState } from "@/components/ui/surfaces";
import { requireVerifiedIdentity } from "@/server/auth/identity";
import { getSpendingAnalytics } from "@/server/analytics/queries";
function money(value: number, currency: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(value / 100); }
export default async function AnalyticsPage() {
  await requireVerifiedIdentity(); const data = await getSpendingAnalytics(); const maxCategory = data.categories[0]?.amount ?? 1; const maxMonth = Math.max(1, ...data.months.map((item) => Math.max(item.income, item.spending)));
  return <main id="main-content" className="mx-auto w-full max-w-5xl px-4 py-10 sm:px-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-action">Insights</p><h1 className="mt-2 text-3xl font-semibold">Spending analytics</h1><p className="mt-2 text-muted">Posted activity from the last 12 months. Internal transfers and reversals are excluded.</p></div><Link className="font-semibold text-action underline" href="/dashboard">Back to dashboard</Link></div>
    <div className="mt-8 grid gap-5 sm:grid-cols-3"><Card><p className="text-sm text-muted">Income</p><p className="mt-2 text-2xl font-semibold">{money(data.income, data.currency)}</p></Card><Card><p className="text-sm text-muted">Spending</p><p className="mt-2 text-2xl font-semibold">{money(data.spending, data.currency)}</p></Card><Card><p className="text-sm text-muted">Cash flow</p><p className="mt-2 text-2xl font-semibold">{money(data.cashFlow, data.currency)}</p></Card></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-semibold">Spending by category</h2>{data.categories.length === 0 ? <div className="mt-4"><EmptyState title="No spending data">Posted purchases and payments will appear here.</EmptyState></div> : <div className="mt-5 space-y-4">{data.categories.map((item) => <div key={item.name}><div className="flex justify-between gap-4 text-sm"><span className="font-semibold">{item.name}</span><span>{money(item.amount, data.currency)}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-subtle" role="img" aria-label={item.name + ": " + money(item.amount, data.currency)}><div className="h-full rounded-full bg-action" style={{ width: Math.max(3, item.amount / maxCategory * 100) + "%" }}/></div></div>)}</div>}</Card>
      <Card><h2 className="text-xl font-semibold">Monthly trend</h2>{data.months.length === 0 ? <p className="mt-4 text-muted">No posted activity yet.</p> : <div className="mt-5 space-y-5">{data.months.map((item) => <div key={item.month}><p className="text-sm font-semibold">{item.month}</p><div className="mt-2 grid grid-cols-[4rem_1fr_auto] items-center gap-2 text-xs"><span>Income</span><div className="h-2 bg-subtle"><div className="h-full bg-success" style={{ width: item.income / maxMonth * 100 + "%" }}/></div><span>{money(item.income, data.currency)}</span><span>Spending</span><div className="h-2 bg-subtle"><div className="h-full bg-action" style={{ width: item.spending / maxMonth * 100 + "%" }}/></div><span>{money(item.spending, data.currency)}</span></div></div>)}</div>}</Card></div>
  </main>;
}
