import { notFound } from "next/navigation";
import Link from "next/link";
import { Input, Select } from "@/components/ui/fields";
import { Alert, Card, EmptyState } from "@/components/ui/surfaces";
import { changeAccountRestrictionAction, reviewVerificationAction } from "@/server/staff/actions";
import { getStaffCustomer, requireStaffContext } from "@/server/staff/queries";
function money(value:number,currency:string){return new Intl.NumberFormat('en-US',{style:'currency',currency}).format(value/100)}
export default async function StaffCustomerPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{message?:string}>}){const context=await requireStaffContext();const[{id},query]=await Promise.all([params,searchParams]);const data=await getStaffCustomer(id);if(!data)notFound();const canRestrict=context.roles.some((role)=>role==='fraud_analyst'||role==='administrator');return <main id="main-content" className="mx-auto w-full max-w-7xl px-4 py-10 sm:px-6"><Link className="font-semibold text-action underline" href="/staff/customers">Customer search</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">{data.customer.first_name} {data.customer.last_name}</h1><p className="mt-2 text-muted">{data.customer.contact_email} · {data.customer.verification_status.replaceAll('_',' ')} · {data.customer.account_status}</p></div><span className="rounded-full bg-subtle px-4 py-2 text-sm font-semibold">Customer since {data.customer.customer_since}</span></div>{query.message&&<div className="mt-5"><Alert title={query.message==='failed'?'Staff change not saved':'Staff change saved'} tone={query.message==='failed'?'error':'success'}/></div>}
    <section className="mt-8"><h2 className="text-2xl font-semibold">Accounts</h2>{data.accounts.length===0?<div className="mt-4"><EmptyState title="No accounts"/></div>:<div className="mt-4 grid gap-4 lg:grid-cols-2">{data.accounts.map((account)=><Card key={account.id}><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{account.nickname}</h3><p className="text-sm text-muted">{account.account_type} · {account.masked_account_number}</p></div><span className="capitalize">{account.status}</span></div>{canRestrict&&account.status!=='closed'&&<form action={changeAccountRestrictionAction} className="mt-5 space-y-3"><input type="hidden" name="customerId" value={data.customer.id}/><input type="hidden" name="accountId" value={account.id}/><Select name="status" label="Account status" defaultValue={account.status}><option value="active">Active</option><option value="frozen">Frozen</option><option value="restricted">Restricted</option></Select><Input name="reason" label="Reason code" required minLength={3} maxLength={80}/><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Apply status</button></form>}</Card>)}</div>}</section>
    {canRestrict&&<section className="mt-8"><h2 className="text-2xl font-semibold">Verification review</h2>{data.verifications.length===0?<div className="mt-4"><EmptyState title="No verification records"/></div>:<div className="mt-4 grid gap-4 lg:grid-cols-2">{data.verifications.map((record)=><Card key={record.id}><h3 className="font-semibold">{record.synthetic_fixture_id}</h3><p className="mt-1 text-sm capitalize text-muted">Current status: {record.status.replaceAll('_',' ')}</p><form action={reviewVerificationAction} className="mt-4 space-y-3"><input type="hidden" name="customerId" value={data.customer.id}/><input type="hidden" name="recordId" value={record.id}/><Select name="status" label="Decision" defaultValue={record.status==='pending'?'manual_review':record.status}><option value="verified">Verified</option><option value="failed">Failed</option><option value="manual_review">Manual review</option></Select><Input name="reason" label="Reason code" required minLength={3} maxLength={80}/><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Save review</button></form></Card>)}</div>}</section>}
    <section className="mt-8 grid gap-6 xl:grid-cols-2"><div><h2 className="text-2xl font-semibold">Recent transactions</h2><div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{data.transactions.length===0?<EmptyState title="No transactions"/>:data.transactions.map((item)=><article className="flex justify-between gap-4 p-4" key={item.id}><div><h3 className="font-semibold">{item.description}</h3><p className="text-sm capitalize text-muted">{item.type} · {item.status}</p></div><span className="font-semibold tabular-nums">{item.direction==='debit'?'−':'+'}{money(item.amount_minor,item.currency)}</span></article>)}</div></div><div><h2 className="text-2xl font-semibold">Recent transfers</h2><div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{data.transfers.length===0?<EmptyState title="No transfers"/>:data.transfers.map((item)=><article className="flex justify-between gap-4 p-4" key={item.id}><div><h3 className="font-semibold">Transfer</h3><p className="text-sm capitalize text-muted">{item.status} · {new Date(item.created_at).toLocaleString('en-US')}</p></div><span className="font-semibold tabular-nums">{money(item.amount_minor,item.currency)}</span></article>)}</div></div></section>
    {data.security_events.length>0&&<section className="mt-8"><h2 className="text-2xl font-semibold">Security events</h2><div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{data.security_events.map((event)=><article className="grid gap-1 p-4 sm:grid-cols-[1fr_auto]" key={event.id}><span className="font-semibold capitalize">{event.event_type.replaceAll('_',' ')}</span><time className="text-sm text-muted">{new Date(event.occurred_at).toLocaleString('en-US')}</time></article>)}</div></section>}
  </main>}
