-- Milestone A simulated credit accounts, cards, purchases, refunds, payments and controls.
insert into private.ledger_accounts(id,class,normal_side,currency,system_code) values(gen_random_uuid(),'liability','credit','USD','SIMULATED_CARD_MERCHANT_CLEARING_USD') on conflict(system_code) do nothing;
insert into private.account_balances(ledger_account_id) select id from private.ledger_accounts where system_code='SIMULATED_CARD_MERCHANT_CLEARING_USD' on conflict do nothing;
alter table public.credit_accounts add column statement_balance_minor bigint not null default 0 check(statement_balance_minor>=0),add column minimum_payment_minor bigint not null default 0 check(minimum_payment_minor>=0),add column next_due_date date;
alter table public.cards add unique(id,customer_id);
create table public.card_alert_preferences(id uuid primary key default gen_random_uuid(),customer_id uuid not null references public.customers(id),card_id uuid not null unique,purchase_alerts boolean not null default true,threshold_minor bigint not null default 0 check(threshold_minor>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(id,customer_id),foreign key(card_id,customer_id) references public.cards(id,customer_id));
alter table public.card_alert_preferences enable row level security;revoke all on public.card_alert_preferences from public,anon,authenticated,service_role;grant select on public.card_alert_preferences to authenticated;create policy owner_read on public.card_alert_preferences for select to authenticated using(private.owns_customer(customer_id));create index card_alert_preferences_customer_idx on public.card_alert_preferences(customer_id);create trigger touch_updated_at before update on public.card_alert_preferences for each row execute function private.touch_updated_at();

create or replace function private.refresh_credit_due(p_credit_account_id uuid) returns void language plpgsql security definer set search_path='' as $$
declare v_outstanding bigint;
begin select greatest(b.net_debit_minor,0) into v_outstanding from public.credit_accounts ca join private.account_balances b on b.ledger_account_id=ca.ledger_account_id where ca.id=p_credit_account_id;update public.credit_accounts set statement_balance_minor=v_outstanding,minimum_payment_minor=case when v_outstanding=0 then 0 else least(v_outstanding,greatest(2500,(v_outstanding*2+99)/100)) end where id=p_credit_account_id;end;$$;

create or replace function public.open_current_credit_card(p_credit_limit_minor bigint,p_cardholder text,p_idempotency_key text)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_customer public.customers%rowtype;v_name text:=btrim(p_cardholder);v_hash text;v_request private.idempotency_requests%rowtype;v_credit uuid:=gen_random_uuid();v_ledger uuid:=gen_random_uuid();v_card uuid:=gen_random_uuid();v_due_day smallint;
begin
 if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;if p_credit_limit_minor not between 50000 and 5000000 or char_length(v_name) not between 1 and 120 then raise exception 'Invalid credit card request' using errcode='22023';end if;
 select * into v_customer from public.customers where auth_user_id=v_user and verification_status='verified' and account_status='active' for update;if not found then raise exception 'Customer unavailable' using errcode='42501';end if;if(select count(*) from public.credit_accounts where customer_id=v_customer.id and status<>'closed')>=5 then raise exception 'Credit account limit reached' using errcode='23514';end if;
 v_hash:=encode(extensions.digest(concat_ws('|',v_customer.id,p_credit_limit_minor,v_name),'sha256'),'hex');insert into private.idempotency_requests(actor_id,operation,key,payload_hash,state) values(v_user,'open_credit_card',p_idempotency_key,v_hash,'processing') on conflict(actor_id,operation,key) do nothing;select * into v_request from private.idempotency_requests where actor_id=v_user and operation='open_credit_card' and key=p_idempotency_key for update;if v_request.payload_hash<>v_hash then raise exception 'Idempotency payload mismatch' using errcode='23505';end if;if v_request.state='succeeded' then return v_request.result_id;end if;
 v_due_day:=least(extract(day from now())::smallint,28);insert into private.ledger_accounts(id,class,normal_side,currency) values(v_ledger,'asset','debit','USD');insert into private.account_balances(ledger_account_id) values(v_ledger);insert into public.credit_accounts(id,customer_id,ledger_account_id,currency,credit_limit_minor,cycle_day,due_day,next_due_date,status) values(v_credit,v_customer.id,v_ledger,'USD',p_credit_limit_minor,v_due_day,v_due_day,(date_trunc('month',now())+interval '1 month'+(v_due_day-1)*interval '1 day')::date,'active');insert into public.cards(id,customer_id,credit_account_id,currency,synthetic_token,last_four,cardholder,status,purchase_limit_minor) values(v_card,v_customer.id,v_credit,'USD','SIM-CARD-'||upper(substr(replace(v_card::text,'-',''),1,20)),lpad((mod(abs(hashtextextended(v_card::text,0)),10000))::text,4,'0'),v_name,'active',p_credit_limit_minor);insert into public.card_alert_preferences(customer_id,card_id) values(v_customer.id,v_card);update private.idempotency_requests set state='succeeded',result_type='card',result_id=v_card where id=v_request.id;insert into private.audit_logs(actor_id,actor_role,action,resource_type,resource_id,correlation_id) values(v_user,'customer','card.opened','card',v_card,gen_random_uuid());return v_card;
end;$$;

create or replace function public.get_current_credit_balances()
returns table(credit_account_id uuid,current_balance_minor bigint,pending_minor bigint,available_credit_minor bigint,currency text) language sql stable security definer set search_path='' as $$
 select ca.id,greatest(b.net_debit_minor,0),coalesce((select sum(h.amount_minor) from private.balance_holds h where h.ledger_account_id=ca.ledger_account_id and h.status='active' and h.expires_at>now()),0),greatest(ca.credit_limit_minor-greatest(b.net_debit_minor,0)-coalesce((select sum(h.amount_minor) from private.balance_holds h where h.ledger_account_id=ca.ledger_account_id and h.status='active' and h.expires_at>now()),0),0),ca.currency from public.credit_accounts ca join public.customers c on c.id=ca.customer_id join private.account_balances b on b.ledger_account_id=ca.ledger_account_id where c.auth_user_id=auth.uid() and private.session_is_active()
$$;

create or replace function public.authorize_current_card_purchase(p_card_id uuid,p_merchant text,p_amount_minor bigint,p_category text,p_location text,p_expires_at timestamptz,p_idempotency_key text)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_card public.cards%rowtype;v_credit public.credit_accounts%rowtype;v_customer uuid;v_balance bigint;v_held bigint;v_hash text;v_request private.idempotency_requests%rowtype;v_hold uuid;v_tx uuid;v_merchant text:=btrim(p_merchant);
begin
 if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;if p_amount_minor<=0 or char_length(v_merchant) not between 1 and 200 or p_expires_at<=now() then raise exception 'Invalid purchase' using errcode='22023';end if;
 select ca.* into v_credit from public.credit_accounts ca join public.customers c on c.id=ca.customer_id where ca.id=(select credit_account_id from public.cards where id=p_card_id) and c.auth_user_id=v_user and c.account_status='active';v_customer:=v_credit.customer_id;select * into v_card from public.cards where id=p_card_id and customer_id=v_customer;if v_card.id is null or v_card.status<>'active' or v_credit.status<>'active' or p_amount_minor>v_card.purchase_limit_minor then raise exception 'Card unavailable' using errcode='42501';end if;
 v_hash:=encode(extensions.digest(concat_ws('|',p_card_id,v_merchant,p_amount_minor,coalesce(p_category,''),coalesce(p_location,''),p_expires_at),'sha256'),'hex');insert into private.idempotency_requests(actor_id,operation,key,payload_hash,state) values(v_user,'card_authorization',p_idempotency_key,v_hash,'processing') on conflict(actor_id,operation,key) do nothing;select * into v_request from private.idempotency_requests where actor_id=v_user and operation='card_authorization' and key=p_idempotency_key for update;if v_request.payload_hash<>v_hash then raise exception 'Idempotency payload mismatch' using errcode='23505';end if;if v_request.state='succeeded' then return v_request.result_id;end if;
 select net_debit_minor into v_balance from private.account_balances where ledger_account_id=v_credit.ledger_account_id for update;select coalesce(sum(amount_minor),0) into v_held from private.balance_holds where ledger_account_id=v_credit.ledger_account_id and status='active' and expires_at>now();if greatest(v_balance,0)+v_held+p_amount_minor>v_credit.credit_limit_minor then raise exception 'Insufficient available credit' using errcode='P0001';end if;
 insert into private.balance_holds(ledger_account_id,operation_id,amount_minor,status,expires_at) values(v_credit.ledger_account_id,gen_random_uuid(),p_amount_minor,'active',p_expires_at) returning id into v_hold;insert into public.card_transactions(customer_id,card_id,hold_id,merchant,amount_minor,currency,category,location,kind,status) values(v_customer,p_card_id,v_hold,v_merchant,p_amount_minor,v_card.currency,coalesce(nullif(btrim(p_category),''),'Other'),nullif(btrim(p_location),''),'purchase','pending') returning id into v_tx;update private.idempotency_requests set state='succeeded',result_type='card_transaction',result_id=v_tx where id=v_request.id;return v_tx;
end;$$;

create or replace function public.settle_current_card_purchase(p_card_transaction_id uuid,p_idempotency_key text)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_tx public.card_transactions%rowtype;v_credit public.credit_accounts%rowtype;v_hash text;v_journal uuid;v_clearing uuid;
begin
 if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;select ct.* into v_tx from public.card_transactions ct join public.customers c on c.id=ct.customer_id where ct.id=p_card_transaction_id and c.auth_user_id=v_user for update of ct;if not found then raise exception 'Purchase unavailable' using errcode='42501';end if;select ca.* into v_credit from public.credit_accounts ca join public.cards c on c.credit_account_id=ca.id where c.id=v_tx.card_id;select id into v_clearing from private.ledger_accounts where system_code='SIMULATED_CARD_MERCHANT_CLEARING_USD';v_hash:=encode(extensions.digest(concat_ws('|',v_tx.id,v_tx.amount_minor,v_tx.currency),'sha256'),'hex');v_journal:=private.post_ledger_operation(v_user,'card_purchase',p_idempotency_key,v_hash,v_credit.ledger_account_id,v_clearing,v_tx.amount_minor,now(),gen_random_uuid());if v_tx.status='posted' then if v_tx.journal_id<>v_journal then raise exception 'Purchase mismatch' using errcode='23505';end if;return v_tx.id;end if;if v_tx.status<>'pending' then raise exception 'Purchase cannot settle' using errcode='23514';end if;update private.balance_holds set status='captured' where id=v_tx.hold_id and status='active';if not found then raise exception 'Purchase hold unavailable' using errcode='23514';end if;update public.card_transactions set status='posted',journal_id=v_journal where id=v_tx.id;perform private.refresh_credit_due(v_credit.id);insert into private.audit_logs(actor_id,actor_role,action,resource_type,resource_id,correlation_id) values(v_user,'customer','card.purchase_posted','card_transaction',v_tx.id,gen_random_uuid());return v_tx.id;
end;$$;

create or replace function public.release_current_card_purchase(p_card_transaction_id uuid) returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_hold uuid;begin if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;update public.card_transactions ct set status='released' from public.customers c where ct.id=p_card_transaction_id and ct.customer_id=c.id and c.auth_user_id=v_user and ct.status='pending' returning ct.hold_id into v_hold;if v_hold is null then raise exception 'Purchase unavailable' using errcode='42501';end if;update private.balance_holds set status='released' where id=v_hold and status='active';end;$$;

create or replace function public.refund_current_card_purchase(p_original_id uuid,p_amount_minor bigint,p_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_original public.card_transactions%rowtype;v_credit public.credit_accounts%rowtype;v_hash text;v_request private.idempotency_requests%rowtype;v_journal uuid;v_clearing uuid;v_refund uuid;v_refunded bigint;
begin if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;select ct.* into v_original from public.card_transactions ct join public.customers c on c.id=ct.customer_id where ct.id=p_original_id and c.auth_user_id=v_user for update of ct;if not found or v_original.status<>'posted' or v_original.kind<>'purchase' or p_amount_minor<=0 then raise exception 'Purchase unavailable' using errcode='42501';end if;v_hash:=encode(extensions.digest(concat_ws('|',p_original_id,p_amount_minor,v_original.currency),'sha256'),'hex');select * into v_request from private.idempotency_requests where actor_id=v_user and operation='card_refund' and key=p_idempotency_key;if found then if v_request.payload_hash<>v_hash then raise exception 'Idempotency payload mismatch' using errcode='23505';end if;if v_request.state='succeeded' then select id into v_refund from public.card_transactions where journal_id=v_request.result_id;return v_refund;end if;end if;select coalesce(sum(amount_minor),0) into v_refunded from public.card_transactions where original_id=p_original_id and kind='refund' and status='posted';if v_refunded+p_amount_minor>v_original.amount_minor then raise exception 'Refund exceeds purchase' using errcode='23514';end if;select ca.* into v_credit from public.credit_accounts ca join public.cards c on c.credit_account_id=ca.id where c.id=v_original.card_id;select id into v_clearing from private.ledger_accounts where system_code='SIMULATED_CARD_MERCHANT_CLEARING_USD';v_journal:=private.post_ledger_operation(v_user,'card_refund',p_idempotency_key,v_hash,v_clearing,v_credit.ledger_account_id,p_amount_minor,now(),gen_random_uuid());insert into public.card_transactions(customer_id,card_id,journal_id,merchant,amount_minor,currency,category,location,kind,status,original_id) values(v_original.customer_id,v_original.card_id,v_journal,v_original.merchant,p_amount_minor,v_original.currency,v_original.category,v_original.location,'refund','posted',v_original.id) returning id into v_refund;perform private.refresh_credit_due(v_credit.id);return v_refund;end;$$;

create or replace function public.pay_current_credit_card(p_card_id uuid,p_account_id uuid,p_amount_minor bigint,p_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_card public.cards%rowtype;v_credit public.credit_accounts%rowtype;v_account public.accounts%rowtype;v_customer public.customers%rowtype;v_source uuid;v_hash text;v_journal uuid;v_tx uuid;v_outstanding bigint;
begin if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;select * into v_customer from public.customers where auth_user_id=v_user and account_status='active';select * into v_card from public.cards where id=p_card_id and customer_id=v_customer.id;select * into v_credit from public.credit_accounts where id=v_card.credit_account_id and customer_id=v_customer.id and status<>'closed';select * into v_account from public.accounts where id=p_account_id and customer_id=v_customer.id and status='active';if v_card.id is null or v_account.id is null or p_amount_minor<=0 then raise exception 'Payment unavailable' using errcode='42501';end if;select net_debit_minor into v_outstanding from private.account_balances where ledger_account_id=v_credit.ledger_account_id for update;if p_amount_minor>greatest(v_outstanding,0) then raise exception 'Payment exceeds balance' using errcode='23514';end if;select id into v_source from private.ledger_accounts where account_id=v_account.id;v_hash:=encode(extensions.digest(concat_ws('|',v_card.id,v_account.id,p_amount_minor,v_card.currency),'sha256'),'hex');v_journal:=private.post_customer_debit_operation(v_user,'card_payment',p_idempotency_key,v_hash,v_source,v_credit.ledger_account_id,p_amount_minor,gen_random_uuid());select id into v_tx from public.transactions where journal_id=v_journal and type='card_payment';if v_tx is null then insert into public.transactions(customer_id,account_id,operation_id,journal_id,type,direction,amount_minor,currency,description,category,status,posted_at) values(v_customer.id,v_account.id,gen_random_uuid(),v_journal,'card_payment','debit',p_amount_minor,v_account.currency,'Payment to card ending '||v_card.last_four,'Card payment','posted',now()) returning id into v_tx;perform private.refresh_credit_due(v_credit.id);end if;return v_tx;end;$$;

create or replace function public.update_current_card_status(p_card_id uuid,p_action text) returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_old text;v_new text;begin if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;select ca.status into v_old from public.cards ca join public.customers c on c.id=ca.customer_id where ca.id=p_card_id and c.auth_user_id=v_user for update of ca;v_new:=case p_action when 'lock' then 'locked' when 'unlock' then 'active' when 'lost' then 'lost' when 'stolen' then 'stolen' else null end;if v_new is null or (p_action='unlock' and v_old<>'locked') or (p_action<>'unlock' and v_old not in('active','locked')) then raise exception 'Card status transition denied' using errcode='23514';end if;update public.cards set status=v_new where id=p_card_id;insert into private.audit_logs(actor_id,actor_role,action,resource_type,resource_id,correlation_id) values(v_user,'customer','card.'||p_action,'card',p_card_id,gen_random_uuid());end;$$;

create or replace function public.replace_current_card(p_card_id uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_old public.cards%rowtype;v_new uuid:=gen_random_uuid();begin if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;select ca.* into v_old from public.cards ca join public.customers c on c.id=ca.customer_id where ca.id=p_card_id and c.auth_user_id=v_user for update of ca;if not found or v_old.status not in('active','locked','lost','stolen') then raise exception 'Card unavailable' using errcode='42501';end if;update public.cards set status='replaced' where id=v_old.id;insert into public.cards(id,customer_id,credit_account_id,currency,synthetic_token,last_four,cardholder,status,purchase_limit_minor,replaced_card_id) values(v_new,v_old.customer_id,v_old.credit_account_id,v_old.currency,'SIM-CARD-'||upper(substr(replace(v_new::text,'-',''),1,20)),lpad((mod(abs(hashtextextended(v_new::text,0)),10000))::text,4,'0'),v_old.cardholder,'active',v_old.purchase_limit_minor,v_old.id);insert into public.card_alert_preferences(customer_id,card_id,purchase_alerts,threshold_minor) select v_old.customer_id,v_new,purchase_alerts,threshold_minor from public.card_alert_preferences where card_id=v_old.id;return v_new;end;$$;

create or replace function public.update_current_card_preferences(p_card_id uuid,p_purchase_limit_minor bigint,p_purchase_alerts boolean,p_threshold_minor bigint) returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_limit bigint;v_customer uuid;begin if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;select ca.credit_limit_minor,c.id into v_limit,v_customer from public.cards card join public.credit_accounts ca on ca.id=card.credit_account_id join public.customers c on c.id=card.customer_id where card.id=p_card_id and c.auth_user_id=v_user and card.status in('active','locked') for update of card;if v_customer is null or p_purchase_limit_minor not between 0 and v_limit or p_threshold_minor<0 then raise exception 'Invalid card preferences' using errcode='22023';end if;update public.cards set purchase_limit_minor=p_purchase_limit_minor where id=p_card_id;update public.card_alert_preferences set purchase_alerts=p_purchase_alerts,threshold_minor=p_threshold_minor where card_id=p_card_id and customer_id=v_customer;end;$$;

revoke all on function private.refresh_credit_due(uuid) from public,anon,authenticated,service_role;
revoke all on function public.open_current_credit_card(bigint,text,text),public.get_current_credit_balances(),public.authorize_current_card_purchase(uuid,text,bigint,text,text,timestamptz,text),public.settle_current_card_purchase(uuid,text),public.release_current_card_purchase(uuid),public.refund_current_card_purchase(uuid,bigint,text),public.pay_current_credit_card(uuid,uuid,bigint,text),public.update_current_card_status(uuid,text),public.replace_current_card(uuid),public.update_current_card_preferences(uuid,bigint,boolean,bigint) from public,anon,authenticated,service_role;
grant execute on function public.open_current_credit_card(bigint,text,text),public.get_current_credit_balances(),public.authorize_current_card_purchase(uuid,text,bigint,text,text,timestamptz,text),public.settle_current_card_purchase(uuid,text),public.release_current_card_purchase(uuid),public.refund_current_card_purchase(uuid,bigint,text),public.pay_current_credit_card(uuid,uuid,bigint,text),public.update_current_card_status(uuid,text),public.replace_current_card(uuid),public.update_current_card_preferences(uuid,bigint,boolean,bigint) to authenticated;
