-- Milestone A synthetic check upload, review and exactly-once acceptance.
alter table public.check_deposits add column upload_state text not null default 'pending_upload' check(upload_state in('pending_upload','ready')),add column mime_type text check(mime_type in('image/png','image/jpeg')),add column size_bytes bigint check(size_bytes between 1 and 5242880);

create policy bank_checks_insert on storage.objects for insert to authenticated with check(
 bucket_id='bank-test-checks' and exists(select 1 from public.check_deposits d where d.object_key=name and d.upload_state='pending_upload' and private.owns_customer(d.customer_id))
);
create policy bank_checks_delete_pending on storage.objects for delete to authenticated using(
 bucket_id='bank-test-checks' and exists(select 1 from public.check_deposits d where d.object_key=name and d.upload_state='pending_upload' and private.owns_customer(d.customer_id))
);

create or replace function public.begin_current_check_deposit(p_deposit_id uuid,p_account_id uuid,p_amount_minor bigint,p_object_key text,p_mime_type text,p_size_bytes bigint)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_customer public.customers%rowtype;v_account public.accounts%rowtype;v_extension text;
begin
 if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;if p_amount_minor not between 1 and 100000000 or p_mime_type not in('image/png','image/jpeg') or p_size_bytes not between 1 and 5242880 then raise exception 'Invalid check deposit' using errcode='22023';end if;
 select * into v_customer from public.customers where auth_user_id=v_user and verification_status='verified' and account_status='active';select * into v_account from public.accounts where id=p_account_id and customer_id=v_customer.id and status='active';if v_customer.id is null or v_account.id is null then raise exception 'Account unavailable' using errcode='42501';end if;v_extension:=case p_mime_type when 'image/png' then '.png' else '.jpg' end;if p_object_key<>v_customer.id||'/'||p_deposit_id||v_extension then raise exception 'Invalid object key' using errcode='22023';end if;
 insert into public.check_deposits(id,customer_id,account_id,amount_minor,currency,object_key,status,upload_state,mime_type,size_bytes) values(p_deposit_id,v_customer.id,v_account.id,p_amount_minor,v_account.currency,p_object_key,'submitted','pending_upload',p_mime_type,p_size_bytes);return p_deposit_id;
end;$$;

create or replace function public.finalize_current_check_upload(p_deposit_id uuid) returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_deposit public.check_deposits%rowtype;v_object storage.objects%rowtype;
begin
 if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;select d.* into v_deposit from public.check_deposits d join public.customers c on c.id=d.customer_id where d.id=p_deposit_id and c.auth_user_id=v_user for update of d;if not found or v_deposit.upload_state<>'pending_upload' then raise exception 'Deposit unavailable' using errcode='42501';end if;select * into v_object from storage.objects where bucket_id='bank-test-checks' and name=v_deposit.object_key;if not found or coalesce((v_object.metadata->>'size')::bigint,0)<>v_deposit.size_bytes or coalesce(v_object.metadata->>'mimetype','')<>v_deposit.mime_type then raise exception 'Uploaded object mismatch' using errcode='23514';end if;update public.check_deposits set upload_state='ready' where id=p_deposit_id;insert into private.audit_logs(actor_id,actor_role,action,resource_type,resource_id,correlation_id) values(v_user,'customer','check_deposit.submitted','check_deposit',p_deposit_id,gen_random_uuid());
end;$$;

create or replace function public.abandon_current_check_upload(p_deposit_id uuid) returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();begin if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;delete from public.check_deposits d using public.customers c where d.id=p_deposit_id and d.customer_id=c.id and c.auth_user_id=v_user and d.upload_state='pending_upload';if not found then raise exception 'Deposit unavailable' using errcode='42501';end if;end;$$;

create or replace function public.begin_current_check_review(p_deposit_id uuid) returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();begin if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;update public.check_deposits d set status='reviewing' from public.customers c where d.id=p_deposit_id and d.customer_id=c.id and c.auth_user_id=v_user and d.status='submitted' and d.upload_state='ready';if not found then raise exception 'Deposit unavailable' using errcode='42501';end if;end;$$;

create or replace function public.resolve_current_check_deposit(p_deposit_id uuid,p_outcome text,p_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_deposit public.check_deposits%rowtype;v_ledger uuid;v_cash uuid;v_hash text;v_journal uuid;v_request private.idempotency_requests%rowtype;v_tx uuid;
begin
 if v_user is null or not private.session_is_active() then raise exception 'Active session required' using errcode='42501';end if;if p_outcome not in('accept','reject') then raise exception 'Invalid outcome' using errcode='22023';end if;select d.* into v_deposit from public.check_deposits d join public.customers c on c.id=d.customer_id where d.id=p_deposit_id and c.auth_user_id=v_user for update of d;if not found or v_deposit.upload_state<>'ready' then raise exception 'Deposit unavailable' using errcode='42501';end if;
 v_hash:=encode(extensions.digest(concat_ws('|',v_deposit.id,p_outcome,v_deposit.amount_minor,v_deposit.currency),'sha256'),'hex');
 if p_outcome='reject' then insert into private.idempotency_requests(actor_id,operation,key,payload_hash,state) values(v_user,'check_rejection',p_idempotency_key,v_hash,'processing') on conflict(actor_id,operation,key) do nothing;select * into v_request from private.idempotency_requests where actor_id=v_user and operation='check_rejection' and key=p_idempotency_key for update;if v_request.payload_hash<>v_hash then raise exception 'Idempotency payload mismatch' using errcode='23505';end if;if v_request.state='succeeded' then return v_deposit.id;end if;if v_deposit.status<>'reviewing' then raise exception 'Deposit not reviewing' using errcode='23514';end if;update public.check_deposits set status='rejected',reviewed_at=now() where id=v_deposit.id;update private.idempotency_requests set state='succeeded',result_type='check_deposit',result_id=v_deposit.id where id=v_request.id;insert into private.audit_logs(actor_id,actor_role,action,resource_type,resource_id,correlation_id) values(v_user,'synthetic_reviewer','check_deposit.rejected','check_deposit',v_deposit.id,gen_random_uuid());return v_deposit.id;end if;
 select id into v_ledger from private.ledger_accounts where account_id=v_deposit.account_id;select id into v_cash from private.ledger_accounts where system_code='SIMULATOR_CASH_USD';v_journal:=private.post_ledger_operation(v_user,'check_deposit',p_idempotency_key,v_hash,v_cash,v_ledger,v_deposit.amount_minor,now(),gen_random_uuid());if v_deposit.status='accepted' then if v_deposit.journal_id<>v_journal then raise exception 'Deposit mismatch' using errcode='23505';end if;return v_deposit.id;end if;if v_deposit.status<>'reviewing' then raise exception 'Deposit not reviewing' using errcode='23514';end if;update public.check_deposits set status='accepted',reviewed_at=now(),journal_id=v_journal where id=v_deposit.id;insert into public.transactions(customer_id,account_id,operation_id,journal_id,type,direction,amount_minor,currency,description,category,status,posted_at) values(v_deposit.customer_id,v_deposit.account_id,gen_random_uuid(),v_journal,'deposit','credit',v_deposit.amount_minor,v_deposit.currency,'Synthetic check deposit','Income','posted',now()) returning id into v_tx;insert into private.audit_logs(actor_id,actor_role,action,resource_type,resource_id,correlation_id) values(v_user,'synthetic_reviewer','check_deposit.accepted','check_deposit',v_deposit.id,gen_random_uuid());insert into private.outbox_events(event_type,aggregate_type,aggregate_id,payload_version,dedupe_key) values('check_deposit.accepted','check_deposit',v_deposit.id,1,'check_deposit.accepted:'||v_deposit.id);return v_deposit.id;
end;$$;

revoke all on function public.begin_current_check_deposit(uuid,uuid,bigint,text,text,bigint),public.finalize_current_check_upload(uuid),public.abandon_current_check_upload(uuid),public.begin_current_check_review(uuid),public.resolve_current_check_deposit(uuid,text,text) from public,anon,authenticated,service_role;
grant execute on function public.begin_current_check_deposit(uuid,uuid,bigint,text,text,bigint),public.finalize_current_check_upload(uuid),public.abandon_current_check_upload(uuid),public.begin_current_check_review(uuid),public.resolve_current_check_deposit(uuid,text,text) to authenticated;
