import Link from "next/link";
import { Alert, Card, EmptyState } from "@/components/ui/surfaces";
import { requireVerifiedIdentity } from "@/server/auth/identity";
import { markAllNotificationsReadAction, markNotificationReadAction, updateNotificationPreferenceAction } from "@/server/notifications/actions";
import { getNotificationCenter } from "@/server/notifications/queries";
export default async function NotificationsPage({ searchParams }: { searchParams: Promise<{ message?: string }> }) {
  await requireVerifiedIdentity(); const [data, query] = await Promise.all([getNotificationCenter(), searchParams]);
  return <main id="main-content" className="mx-auto w-full max-w-5xl px-4 py-10 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-action">Updates</p><h1 className="mt-2 text-3xl font-semibold">Notifications</h1><p className="mt-2 text-muted">{data.unread} unread · persisted from banking events</p></div><div className="flex gap-4"><Link className="font-semibold text-action underline" href="/dashboard">Dashboard</Link>{data.unread > 0 && <form action={markAllNotificationsReadAction}><button className="font-semibold text-action underline">Mark all read</button></form>}</div></div>
    {query.message && <div className="mt-5"><Alert title={query.message === "preference" ? "Preference saved" : "Notifications marked read"} tone="success"/></div>}
    <div className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><section><h2 className="text-xl font-semibold">History</h2>{data.notifications.length === 0 ? <div className="mt-4"><EmptyState title="No notifications">New banking activity will appear here.</EmptyState></div> : <div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{data.notifications.map((item) => <article className={item.read_at ? "p-4" : "bg-subtle p-4"} key={item.id}><div className="flex justify-between gap-4"><div><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-sm text-muted">{item.body}</p><p className="mt-2 text-xs text-muted">{new Date(item.created_at).toLocaleString("en-US")}</p></div>{!item.read_at && <form action={markNotificationReadAction}><input type="hidden" name="notificationId" value={item.id}/><button className="min-h-11 font-semibold text-action underline">Mark read</button></form>}</div></article>)}</div>}</section>
      <aside><Card><h2 className="text-xl font-semibold">In-app preferences</h2><p className="mt-2 text-sm text-muted">Turn off future notifications by event type. Existing history remains available.</p><div className="mt-5 space-y-4">{data.types.length === 0 ? <p className="text-sm text-muted">Preferences appear after the first event.</p> : data.types.map((type) => { const enabled = data.preferences.find((item) => item.type === type)?.enabled ?? true; return <form action={updateNotificationPreferenceAction} className="flex items-center justify-between gap-3" key={type}><input type="hidden" name="type" value={type}/><input type="hidden" name="enabled" value={enabled ? "false" : "true"}/><span className="text-sm">{type.replaceAll(".", " ")}</span><button className="min-h-11 font-semibold text-action underline">{enabled ? "Turn off" : "Turn on"}</button></form>; })}</div></Card></aside></div>
  </main>;
}
