export type PublicPage = {
  slug: string;
  eyebrow: string;
  title: string;
  summary: string;
  availability: string;
  features: Array<{ title: string; description: string }>;
  guidance: string;
};

export const publicPages: PublicPage[] = [
  { slug:"checking",eyebrow:"Personal banking",title:"Checking for everyday money",summary:"Manage deposits, payments and everyday spending from one clear account view.",availability:"Checking accounts are available to verified customers in online banking.",features:[{title:"Clear account activity",description:"Review balances and posted transactions."},{title:"Money movement",description:"Transfers and bill payments use review screens and saved receipts."},{title:"Account controls",description:"Manage nicknames, statements and preferences from one protected area."}],guidance:"Open an account online and manage it securely from your dashboard." },
  { slug:"savings",eyebrow:"Personal banking",title:"Savings built around clear goals",summary:"Keep money set aside while maintaining a clear view of account activity.",availability:"Savings accounts are available to verified customers in online banking.",features:[{title:"Separate savings",description:"Keep savings distinct from daily checking activity."},{title:"Transparent balances",description:"See ledger and available balances together."},{title:"Statement history",description:"Generate statement periods and private PDF downloads."}],guidance:"Open checking and savings accounts and manage both from one dashboard." },
  { slug:"credit-cards",eyebrow:"Personal banking",title:"Credit cards with controls built in",summary:"Manage purchases, payments, spending limits and card security in one place.",availability:"Verified customers can open and manage credit cards from the dashboard.",features:[{title:"Protected card details",description:"Sensitive card identifiers remain masked throughout online banking."},{title:"Limits and holds",description:"Authorization holds and available credit update with account activity."},{title:"Card controls",description:"Lock a card, request a replacement and manage alerts."}],guidance:"Review terms and account activity carefully before confirming a card action." },
  { slug:"mortgage",eyebrow:"Home lending",title:"A clearer mortgage journey",summary:"Explore applications, amortization, escrow and payments.",availability:"Mortgage application and account servicing are available after verified sign-in.",features:[{title:"Application status",description:"Follow an application from submission through its decision."},{title:"Amortization",description:"See principal, interest and escrow details clearly."},{title:"Payment history",description:"Review completed payments and the remaining balance."}],guidance:"Explore home lending and manage an existing mortgage from online banking." },
  { slug:"auto-financing",eyebrow:"Auto",title:"Plan and manage an auto loan",summary:"Follow a loan from opening through regular payments.",availability:"Personal and auto loans are available after verified sign-in.",features:[{title:"Clear loan terms",description:"Principal, term and rate information appear together."},{title:"Payment breakdown",description:"Each payment separates principal and interest."},{title:"Persistent history",description:"Review completed payments and remaining principal."}],guidance:"Compare the payment amount and term before opening a loan." },
  { slug:"investing",eyebrow:"Investing",title:"Invest with a complete account view",summary:"Review holdings, prices, cash and performance from one dashboard.",availability:"Investment accounts, funding and trades are available after verified sign-in.",features:[{title:"Investment choices",description:"Browse available instruments with current account pricing."},{title:"Holdings and cash",description:"Positions and cash update with investment activity."},{title:"Performance context",description:"Accessible summaries show holdings and market values."}],guidance:"Investments involve risk, including possible loss of principal." },
  { slug:"education",eyebrow:"Financial education",title:"Learn how your banking works",summary:"Understand balances, transactions, security and responsible money management.",availability:"Educational guidance is available now across BANK products.",features:[{title:"Balance basics",description:"Learn the difference between ledger and available balances."},{title:"Security habits",description:"Use unique credentials and review account activity regularly."},{title:"Money movement",description:"Understand transfers, bill payments and card activity."}],guidance:"Guidance is general education and is not financial, tax or legal advice." },
  { slug:"business-banking",eyebrow:"Business",title:"Tools for your business journey",summary:"A focused workspace for cash flow, payments and account controls.",availability:"Business banking information is available; transactional business accounts are coming later.",features:[{title:"Cash-flow overview",description:"Organize balances, inflows and upcoming obligations."},{title:"Payments",description:"Use clear authorization and receipt controls."},{title:"Team security",description:"Delegated access uses explicit roles and audit history."}],guidance:"Contact BANK support for current business product availability." },
  { slug:"travel",eyebrow:"Travel",title:"Plan more. Enjoy every mile.",summary:"Bring travel planning, everyday spending and account controls together before your next trip.",availability:"Travel tools and card benefits vary by product.",features:[{title:"Travel-ready cards",description:"Explore card options designed for purchases on the go."},{title:"Account controls",description:"Manage card status and purchase alerts from online banking."},{title:"Clear activity",description:"Review travel purchases and payments in one place."}],guidance:"Sign in to review your cards or explore available credit card options." },
  { slug:"commercial",eyebrow:"Commercial",title:"Commercial banking architecture",summary:"See how complex treasury and permission needs would fit the platform’s security model.",availability:"Commercial services are informational only and are not scheduled as a transactional product.",features:[{title:"Treasury boundaries",description:"High-value workflows would require scoped capabilities and strong approval controls."},{title:"Operational visibility",description:"Jobs, outbox events and reconciliation provide traceable processing."},{title:"Relationship support",description:"Future support work will use secure, customer-scoped messages."}],guidance:"No treasury, lending or commercial account service is offered." },
  { slug:"wealth-management",eyebrow:"Wealth management",title:"A connected view across financial goals",summary:"See how investments, lending and cash fit together.",availability:"Wealth management information and self-directed investing are available.",features:[{title:"Connected overview",description:"Bring account and investment information into one clear view."},{title:"Goal context",description:"Education and analytics help explain progress."},{title:"Security first",description:"Sensitive changes require verified identity and additional authentication."}],guidance:"Review investment objectives and risk carefully before making a decision." },
  { slug:"security",eyebrow:"Security",title:"Security designed into every layer",summary:"BANK combines verified access, session controls and protected account data.",availability:"The Security Center provides authenticator MFA, device and session controls, and security history.",features:[{title:"Verified identity",description:"Protected routes validate identity and active sessions."},{title:"Session control",description:"Idle, absolute and explicit revocation rules deny stale sessions."},{title:"Protected data",description:"Row policies and narrow commands enforce account ownership."}],guidance:"Use a unique password, enable MFA and review security activity regularly." },
  { slug:"help-center",eyebrow:"Help",title:"How can we help?",summary:"Find help with access, registration and BANK products.",availability:"Self-service guidance and secure support tickets are available.",features:[{title:"Access help",description:"Use password recovery from the sign-in page."},{title:"Account setup",description:"Each registration step is saved and resumes after sign-in."},{title:"Secure support",description:"Sign in to create a private ticket and follow its message history."}],guidance:"Authenticated customers can use secure messages for account support." },
  { slug:"faq",eyebrow:"Help",title:"Frequently asked questions",summary:"Quick answers about BANK accounts and online banking.",availability:"Guidance reflects the current BANK experience.",features:[{title:"How do I open an account?",description:"Create your login, complete account setup and choose checking or savings."},{title:"How do I protect my account?",description:"Use a unique password and enroll an authenticator in the Security Center."},{title:"How do I contact support?",description:"Sign in and open Support from the dashboard to create a secure ticket."},{title:"Does activity persist?",description:"Yes. Profiles and account activity remain available after sign-in."}],guidance:"For access issues, use password recovery. For account help, create a secure support ticket." },
  { slug:"contact",eyebrow:"Contact",title:"Contact BANK support",summary:"Choose the right self-service path for your account.",availability:"Password recovery and authenticated secure tickets are available.",features:[{title:"Account access",description:"Use Forgot password on the sign-in page."},{title:"Product questions",description:"Review product pages or your dashboard for account details."},{title:"Technical support",description:"Sign in and create a secure ticket with saved message history."}],guidance:"Never include a password, authentication code or full card number in a support message." },
];

export const publicPageBySlug = new Map(publicPages.map((page) => [page.slug,page]));
