"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { requireSameOrigin } from "@/server/security/request";
import { requireStaffContext } from "@/server/staff/queries";
function value(data:FormData,key:string){const item=data.get(key);return typeof item==="string"?item:""}async function client(){await requireSameOrigin();await requireStaffContext();return createServerSupabaseClient()}
export async function claimStaffTicketAction(data:FormData){const id=z.uuid().safeParse(value(data,"ticketId"));if(!id.success)redirect("/staff/support");const supabase=await client();const result=await supabase.rpc("staff_claim_support_ticket",{p_ticket_id:id.data});revalidatePath("/staff/support");redirect(`/staff/support/${id.data}?message=${result.error?"failed":"claimed"}`)}
export async function replyStaffTicketAction(data:FormData){const parsed=z.object({id:z.uuid(),body:z.string().trim().min(1).max(10000),visibility:z.enum(["customer","internal"]),status:z.enum(["in_progress","waiting_for_customer","resolved"])}).safeParse({id:value(data,"ticketId"),body:value(data,"body"),visibility:value(data,"visibility"),status:value(data,"status")});if(!parsed.success)redirect("/staff/support");const supabase=await client();const result=await supabase.rpc("staff_reply_support_ticket",{p_ticket_id:parsed.data.id,p_body:parsed.data.body,p_visibility:parsed.data.visibility,p_status:parsed.data.status});revalidatePath(`/staff/support/${parsed.data.id}`);redirect(`/staff/support/${parsed.data.id}?message=${result.error?"failed":"sent"}`)}
export async function changeAccountRestrictionAction(data:FormData){const parsed=z.object({customerId:z.uuid(),accountId:z.uuid(),status:z.enum(["active","frozen","restricted"]),reason:z.string().trim().min(3).max(80)}).safeParse({customerId:value(data,"customerId"),accountId:value(data,"accountId"),status:value(data,"status"),reason:value(data,"reason")});if(!parsed.success)redirect("/staff/customers");const supabase=await client();const result=await supabase.rpc("staff_set_account_restriction",{p_account_id:parsed.data.accountId,p_status:parsed.data.status,p_reason:parsed.data.reason});revalidatePath(`/staff/customers/${parsed.data.customerId}`);redirect(`/staff/customers/${parsed.data.customerId}?message=${result.error?"failed":"account-updated"}`)}
export async function reviewVerificationAction(data:FormData){const parsed=z.object({customerId:z.uuid(),recordId:z.uuid(),status:z.enum(["verified","failed","manual_review"]),reason:z.string().trim().min(3).max(80)}).safeParse({customerId:value(data,"customerId"),recordId:value(data,"recordId"),status:value(data,"status"),reason:value(data,"reason")});if(!parsed.success)redirect("/staff/customers");const supabase=await client();const result=await supabase.rpc("staff_review_verification",{p_record_id:parsed.data.recordId,p_status:parsed.data.status,p_reason:parsed.data.reason});revalidatePath(`/staff/customers/${parsed.data.customerId}`);redirect(`/staff/customers/${parsed.data.customerId}?message=${result.error?"failed":"verification-updated"}`)}
export async function provisionStaffRoleAction(data:FormData){const parsed=z.object({userId:z.uuid(),role:z.enum(["support_agent","fraud_analyst","operations","administrator"]),reason:z.string().trim().min(3).max(80)}).safeParse({userId:value(data,"userId"),role:value(data,"role"),reason:value(data,"reason")});if(!parsed.success)redirect("/staff/team?message=invalid");const supabase=await client();const result=await supabase.rpc("staff_provision_role",{p_auth_user_id:parsed.data.userId,p_role:parsed.data.role,p_reason:parsed.data.reason});redirect(`/staff/team?message=${result.error?"failed":"granted"}`)}
