import "server-only";
import { redirect } from "next/navigation";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { requireVerifiedIdentity } from "@/server/auth/identity";

type StaffContext={roles:string[];auth_user_id:string};
export async function requireStaffContext(){const identity=await requireVerifiedIdentity();if(identity.currentAssuranceLevel!=="aal2")redirect("/security-center?message=step-up-required");const supabase=await createServerSupabaseClient();const result=await supabase.rpc("staff_get_context");if(result.error||!result.data)redirect("/dashboard?message=staff-access-required");return result.data as unknown as StaffContext}
export async function searchStaffCustomers(query:string){const supabase=await createServerSupabaseClient();const result=await supabase.rpc("staff_search_customers",{p_query:query.slice(0,200)});if(result.error)throw new Error("STAFF_CUSTOMER_SEARCH_FAILED");return result.data as unknown as Array<{id:string;first_name:string;last_name:string;contact_email:string;verification_status:string;account_status:string;customer_since:string;created_at:string}>}
export async function getStaffCustomer(id:string){const supabase=await createServerSupabaseClient();const result=await supabase.rpc("staff_get_customer_snapshot",{p_customer_id:id});if(result.error)return null;return result.data as unknown as {customer:{id:string;first_name:string;middle_name:string|null;last_name:string;contact_email:string;phone:string|null;verification_status:string;account_status:string;customer_since:string};accounts:Array<{id:string;nickname:string;masked_account_number:string;account_type:string;currency:string;status:string;opened_at:string}>;transactions:Array<{id:string;type:string;direction:string;amount_minor:number;currency:string;description:string;status:string;created_at:string}>;transfers:Array<{id:string;amount_minor:number;currency:string;status:string;created_at:string}>;verifications:Array<{id:string;synthetic_fixture_id:string;status:string;reason_code:string|null;created_at:string}>;security_events:Array<{id:string;event_type:string;outcome:string;reason_code:string|null;occurred_at:string}>}}
export async function listStaffSupportTickets(){const supabase=await createServerSupabaseClient();const result=await supabase.rpc("staff_list_support_tickets");if(result.error)throw new Error("STAFF_SUPPORT_LIST_FAILED");return result.data as unknown as Array<{id:string;customer_id:string;assigned_staff_id:string|null;subject:string;status:string;first_name:string;last_name:string;contact_email:string;updated_at:string}>}
export async function getStaffSupportTicket(id:string){const supabase=await createServerSupabaseClient();const result=await supabase.rpc("staff_get_support_ticket",{p_ticket_id:id});if(result.error)return null;return result.data as unknown as {ticket:{id:string;customer_id:string;assigned_staff_id:string|null;subject:string;status:string;created_at:string;updated_at:string};messages:Array<{id:string;author_id:string;body:string;visibility:string;created_at:string}>}}
export async function listStaffAuditLogs(){const supabase=await createServerSupabaseClient();const result=await supabase.rpc("staff_list_audit_logs");if(result.error)throw new Error("STAFF_AUDIT_FAILED");return result.data as unknown as Array<{id:string;actor_id:string|null;actor_role:string;action:string;resource_type:string;resource_id:string|null;reason_code:string|null;correlation_id:string;created_at:string}>}
