"use client";
import { useActionState } from "react";
import { Input,Select } from "@/components/ui/fields";
import { SubmitButton } from "@/components/ui/submit-button";
import { Alert } from "@/components/ui/surfaces";
import { fundAccountAction,openAccountAction,renameAccountAction,type AccountActionState } from "@/server/accounts/actions";
const initial:AccountActionState={status:"idle"};
export function OpenAccountForm(){const[state,action]=useActionState(openAccountAction,initial);return <form action={action} className="space-y-5" noValidate>{state.message&&<Alert title="Unable to open account" tone="error">{state.message}</Alert>}<Select name="accountType" label="Account type" required defaultValue="checking" error={state.fieldErrors?.accountType?.[0]}><option value="checking">Checking</option><option value="savings">Savings</option></Select><Input name="nickname" label="Account nickname" required maxLength={80} hint="For example, Everyday checking. You can change this later." error={state.fieldErrors?.nickname?.[0]}/><SubmitButton>Open account</SubmitButton></form>}
export function RenameAccountForm({id,nickname,disabled}:{id:string;nickname:string;disabled:boolean}){const[state,action]=useActionState(renameAccountAction,initial);return <form action={action} className="space-y-4" noValidate><input type="hidden" name="accountId" value={id}/>{state.message&&<Alert title="Unable to update nickname" tone="error">{state.message}</Alert>}<Input name="nickname" label="Account nickname" required maxLength={80} defaultValue={nickname} disabled={disabled} error={state.fieldErrors?.nickname?.[0]}/><SubmitButton className={disabled?"hidden":undefined}>Save nickname</SubmitButton></form>}
export function FundAccountForm({id,disabled,commandKey}:{id:string;disabled:boolean;commandKey:string}){const[state,action]=useActionState(fundAccountAction,initial);return <form action={action} className="space-y-4" noValidate><input type="hidden" name="accountId" value={id}/><input type="hidden" name="commandKey" value={commandKey}/>{state.message&&<Alert title="Unable to add funds" tone="error">{state.message}</Alert>}<Input name="amount" label="Amount" inputMode="decimal" placeholder="100.00" required disabled={disabled} error={state.fieldErrors?.amount?.[0]} hint="Every amount is posted through the balanced ledger."/><SubmitButton className={disabled?"hidden":undefined}>Add funds</SubmitButton></form>}
