import Link from "next/link";
import { Alert, Card, EmptyState } from "@/components/ui/surfaces";
import { requireVerifiedIdentity } from "@/server/auth/identity";
import { reviewMortgageApplicationAction } from "@/server/mortgages/actions";
import { listCurrentMortgages } from "@/server/mortgages/queries";
function money(value: number, currency = "USD") { return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(value / 100); }
export default async function MortgagesPage({ searchParams }: { searchParams: Promise<{ message?: string }> }) {
  await requireVerifiedIdentity(); const [data, query] = await Promise.all([listCurrentMortgages(), searchParams]);
  return <main id="main-content" className="mx-auto w-full max-w-5xl px-4 py-10 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-action">Home lending</p><h1 className="mt-2 text-3xl font-semibold">Mortgages</h1><p className="mt-2 text-muted">Applications, amortized balances, payments and escrow tracking.</p></div><div className="flex gap-4"><Link className="font-semibold text-action underline" href="/dashboard">Dashboard</Link><Link className="rounded-control bg-action px-4 py-3 font-semibold text-white" href="/mortgages/apply">Apply now</Link></div></div>
    {query.message && <div className="mt-5"><Alert title={query.message === "submitted" ? "Application submitted" : "Action not completed"} tone={query.message === "submitted" ? "success" : "error"}/></div>}
    <section className="mt-8"><h2 className="text-2xl font-semibold">Mortgage accounts</h2>{data.mortgages.length === 0 ? <div className="mt-4"><EmptyState title="No mortgage account">Complete an application to create one.</EmptyState></div> : <div className="mt-4 grid gap-5 sm:grid-cols-2">{data.mortgages.map((item) => <Card key={item.id}><p className="text-sm text-muted">Outstanding balance</p><p className="mt-1 text-2xl font-semibold">{money(item.balance?.outstanding_minor ?? 0, item.currency)}</p><p className="mt-3 text-sm text-muted">{(item.rate * 100).toFixed(2)}% APR · {item.term_months} months</p><Link className="mt-4 inline-flex min-h-11 items-center font-semibold text-action underline" href={"/mortgages/" + item.id}>View mortgage</Link></Card>)}</div>}</section>
    <section className="mt-10"><h2 className="text-2xl font-semibold">Applications</h2>{data.applications.length === 0 ? <p className="mt-3 text-muted">No applications yet.</p> : <div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{data.applications.map((item) => <div className="flex flex-wrap items-center justify-between gap-4 p-4" key={item.id}><div><p className="font-semibold">{money(item.requested_amount_minor)} · {item.requested_term_months} months</p><p className="text-sm capitalize text-muted">{item.status}</p></div>{item.status === "submitted" ? <form action={reviewMortgageApplicationAction}><input type="hidden" name="applicationId" value={item.id}/><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Review application</button></form> : item.mortgage_id ? <Link className="font-semibold text-action underline" href={"/mortgages/" + item.mortgage_id}>View account</Link> : null}</div>)}</div>}</section>
  </main>;
}
