import Link from "next/link";
import { Checkbox, Input, Select } from "@/components/ui/fields";
import { Alert, Card, EmptyState } from "@/components/ui/surfaces";
import { requireVerifiedIdentity } from "@/server/auth/identity";
import { deleteDocumentAction, updateAddressAction, updateContactAction, updatePreferencesAction, uploadSyntheticDocumentAction } from "@/server/settings/actions";
import { getCurrentSettings } from "@/server/settings/queries";

const messages: Record<string, string> = { "contact-saved": "Contact details saved", "address-saved": "Address saved", "preferences-saved": "Preferences saved", "document-uploaded": "Document uploaded", "document-deleted": "Document deleted" };
function formatBytes(bytes: number) { return bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ message?: string }> }) {
  await requireVerifiedIdentity(); const [data, query] = await Promise.all([getCurrentSettings(), searchParams]); const success = query.message ? messages[query.message] : undefined;
  return <main id="main-content" className="mx-auto w-full max-w-6xl px-4 py-10 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-action">Profile</p><h1 className="mt-2 text-3xl font-semibold">Settings</h1><p className="mt-2 text-muted">Manage your contact details, address, preferences and private documents.</p></div><Link className="font-semibold text-action underline" href="/dashboard">Back to dashboard</Link></div>
    {query.message && <div className="mt-6">{success ? <Alert title={success} tone="success"/> : <Alert title="Changes were not saved" tone="error">Review the information and try again.</Alert>}</div>}
    <section className="mt-8 grid gap-6 lg:grid-cols-2" aria-label="Profile settings"><Card><h2 className="text-xl font-semibold">Identity</h2><p className="mt-2 text-sm text-muted">Verified identity fields are protected. Contact support if a legal detail needs correction.</p><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-muted">Legal name</dt><dd className="font-semibold">{[data.customer.first_name,data.customer.middle_name,data.customer.last_name].filter(Boolean).join(" ")}</dd></div><div><dt className="text-sm text-muted">Sign-in email</dt><dd className="break-all font-semibold">{data.authEmail}</dd></div><div><dt className="text-sm text-muted">Date of birth</dt><dd className="font-semibold">{data.customer.date_of_birth ?? "Not provided"}</dd></div><div><dt className="text-sm text-muted">Verification</dt><dd className="font-semibold capitalize">{data.customer.verification_status.replaceAll("_", " ")}</dd></div></dl><form action={updateContactAction} className="mt-6 space-y-4"><Input name="displayName" label="Display name" required maxLength={120} defaultValue={data.profile.display_name}/><Input name="phone" label="Phone" type="tel" required maxLength={32} autoComplete="tel" defaultValue={data.customer.phone ?? ""}/><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Save contact details</button></form></Card>
      <Card><h2 className="text-xl font-semibold">Primary home address</h2><form action={updateAddressAction} className="mt-5 space-y-4"><Input name="line1" label="Street address" required maxLength={200} autoComplete="address-line1" defaultValue={data.address?.line1 ?? ""}/><Input name="line2" label="Apartment, suite or unit" maxLength={200} autoComplete="address-line2" defaultValue={data.address?.line2 ?? ""}/><div className="grid gap-4 sm:grid-cols-2"><Input name="city" label="City" required maxLength={100} autoComplete="address-level2" defaultValue={data.address?.city ?? ""}/><Input name="state" label="State or region" maxLength={100} autoComplete="address-level1" defaultValue={data.address?.state ?? ""}/><Input name="postalCode" label="Postal code" required maxLength={20} autoComplete="postal-code" defaultValue={data.address?.postal_code ?? ""}/><Input name="country" label="Country code" required minLength={2} maxLength={2} autoComplete="country" defaultValue={data.address?.country ?? ""}/></div><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Save address</button></form></Card>
      <Card><h2 className="text-xl font-semibold">Display and privacy</h2><form action={updatePreferencesAction} className="mt-5 space-y-4"><Select name="locale" label="Language format" defaultValue={data.preferences?.locale ?? data.profile.locale}><option value="en-US">English (United States)</option><option value="en-GB">English (United Kingdom)</option></Select><Select name="timezone" label="Time zone" defaultValue={data.preferences?.timezone ?? data.profile.timezone}><option value="Africa/Lagos">Africa/Lagos</option><option value="UTC">UTC</option><option value="America/New_York">America/New York</option><option value="America/Chicago">America/Chicago</option><option value="America/Denver">America/Denver</option><option value="America/Los_Angeles">America/Los Angeles</option><option value="Europe/London">Europe/London</option></Select><Checkbox name="hideBalances" label="Hide balances by default" defaultChecked={data.preferences?.hide_balances ?? false}/><Checkbox name="marketingOptIn" label="Receive product updates" defaultChecked={data.preferences?.marketing_opt_in ?? false}/><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Save preferences</button></form></Card>
      <Card><h2 className="text-xl font-semibold">Private documents</h2><p className="mt-2 text-sm text-muted">Upload correspondence or identity documents as a PDF, PNG or JPEG up to 5 MB.</p><form action={uploadSyntheticDocumentAction} className="mt-5 space-y-4"><Select name="kind" label="Document type" defaultValue="correspondence"><option value="correspondence">Correspondence</option><option value="synthetic_identity">Identity document</option></Select><Input name="document" label="Choose file" type="file" required accept="application/pdf,image/png,image/jpeg"/><button className="min-h-11 rounded-control bg-action px-4 font-semibold text-white">Upload document</button></form></Card></section>
    <section className="mt-8" aria-labelledby="documents-heading"><h2 id="documents-heading" className="text-2xl font-semibold">Document history</h2>{data.documents.length === 0 ? <div className="mt-4"><EmptyState title="No documents">Uploaded documents will appear here.</EmptyState></div> : <div className="mt-4 divide-y divide-border rounded-card border border-border bg-surface">{data.documents.map((document) => <article className="flex flex-wrap items-center justify-between gap-4 p-4" key={document.id}><div><h3 className="font-semibold capitalize">{document.kind.replaceAll("synthetic_", "").replaceAll("_", " ")}</h3><p className="text-sm text-muted">{document.mime_type} · {formatBytes(document.size_bytes)} · {new Date(document.created_at).toLocaleString("en-US")}</p></div><div className="flex items-center gap-4">{document.downloadUrl && <a className="font-semibold text-action underline" href={document.downloadUrl}>Download</a>}<form action={deleteDocumentAction}><input type="hidden" name="documentId" value={document.id}/><button className="min-h-11 font-semibold text-danger underline">Delete</button></form></div></article>)}</div>}</section>
  </main>;
}
